#!/bin/bash

TMUX_NAME="portfolio_server"

# Going to directory of project
cd "$(dirname "$0")" || exit
cd ../

# Update git
git pull

# Build project
pnpm i
pnpm run build

# Serve
tmux kill-session -t $TMUX_NAME
tmux new -d -s $TMUX_NAME "pnpm run serve"

echo "Finished"
